spring.application.name=gateway-service
server.port=3000

spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:10.119.6.66:8848}

spring.cloud.gateway.routes[0].id=backend-websocket
spring.cloud.gateway.routes[0].uri=lb:ws://backend-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/websocket/**

spring.cloud.gateway.routes[1].id=backend-api
spring.cloud.gateway.routes[1].uri=lb://backend-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**,/pk/**,/record/**,/ranklist/**,/community/**,/bot/evaluation/**

spring.cloud.gateway.routes[2].id=matching-api
spring.cloud.gateway.routes[2].uri=lb://matching-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/player/**

spring.cloud.gateway.routes[3].id=bot-running-api
spring.cloud.gateway.routes[3].uri=lb://bot-running-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/bot/add/**

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
