spring.application.name=bot-running-service
server.port=3002

spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:10.119.6.66:8848}
kob.internal-token=${KOB_INTERNAL_TOKEN:botgomoku-internal-token}
